[site]
name = "hello"
namespace = "hello"

[database]
url = "ws://127.0.0.1:8000"
ns = "hello"
db = "hello"
user = "root"
pass = "root"

[cache]
max_documents = 10000
ttl_seconds = 300

[apps]
installed = []
