//! Schema synchronisation — Hibernate-style `hbm2ddl.auto=update`.
//!
//! Every compiled DocType registers a [`MetaEntry`] via `inventory::submit!`.
//! On `spotledger migrate` (or at site startup), calling [`ensure_all_schemas`]
//! iterates all registered metas and calls [`ensure_schema`] for each one.
//!
//! ## Rules
//! - **Additive only** — fields are never dropped or renamed automatically.
//!   Removing a field from `DocTypeMeta` simply means the DB column becomes
//!   orphaned data; the framework will ignore it on read.
//! - `DEFINE TABLE … SCHEMAFULL` is idempotent (re-running is safe).
//! - `DEFINE FIELD IF NOT EXISTS …` is idempotent — won't change existing
//!   field definitions that someone altered manually.
//! - Child DocTypes get the extra `parent`/`parenttype`/`parentfield` fields.
//! - A unique index on `name` is created for every non-child table.

use spotledger_core::meta::{DocTypeMeta, FieldType};
use spotledger_core::modules::FM;
use spotledger_core::registry::MetaEntry;

use crate::adapter::DbAdapter;
use crate::document::doctype_to_table;
use crate::error::DbError;

// ── FieldType → SurrealDB type string ────────────────────────────────────────

/// Map a [`FieldType`] to the SurrealDB column type declaration.
///
/// Returns `None` for layout-only fields (Section/Column/Tab break) which
/// are never stored in the DB.
pub fn surql_type(ft: &FieldType) -> Option<&'static str> {
    match ft {
        // Integer storage.
        // Check and Int both use `none | int` so absent fields (NONE) pass SurrealDB v3
        // strict schema validation. `option<int>` only covers null, not NONE (absent).
        // System fields (docstatus, idx) use define_field() directly and are unaffected.
        FieldType::Check | FieldType::Int => Some("none | int"),

        // Float storage
        FieldType::Float | FieldType::Currency | FieldType::Percent | FieldType::Rating
            => Some("float"),

        // Temporal — SurrealDB native datetime for Datetime; string for Date/Time
        // so that Frappe-format strings ("2024-01-15") round-trip without conversion.
        FieldType::Datetime => Some("option<datetime>"),
        FieldType::Date     => Some("option<string>"),
        FieldType::Time     => Some("option<string>"),

        // Child table arrays — embedded JSON array of arbitrary objects.
        // array<any> avoids SCHEMAFULL hierarchical validation on nested keys.
        FieldType::Table | FieldType::TableMultiSelect => Some("array<any>"),

        // Arbitrary JSON blob
        FieldType::Json => Some("any"),

        // Layout-only — no DB column
        FieldType::SectionBreak | FieldType::ColumnBreak | FieldType::TabBreak => None,

        // Everything else is a nullable string
        _ => Some("option<string>"),
    }
}

// ── System fields ─────────────────────────────────────────────────────────────

/// Standard Frappe system fields present on every document table.
///
/// `creation` and `modified` use SurrealDB VALUE expressions so they are
/// always proper `datetime` values generated by the DB engine — no string
/// coercion required from Rust code.
/// • creation: preserved on updates (`$before`), set to `time::now()` on insert.
/// • modified: always overwritten with `time::now()` on every write.
pub const SYSTEM_FIELDS: &[(&str, &str)] = &[
    ("name",        "string"),
    ("doctype",     "option<string>"),
    ("owner",       "string"),
    ("creation",    "datetime VALUE $before OR time::now()"),
    ("modified",    "datetime VALUE time::now()"),
    ("modified_by", "string"),
    ("docstatus",   "int DEFAULT 0"),
    ("idx",         "int DEFAULT 0"),
];

/// Extra fields added only to child-table documents.
pub const CHILD_FIELDS: &[(&str, &str)] = &[
    ("parent",      "string"),
    ("parenttype",  "string"),
    ("parentfield", "string"),
];

// ── Core DDL functions ────────────────────────────────────────────────────────

/// Idempotently ensure the SurrealDB table schema for one DocType.
///
/// **Phase 1** — DDL: emits `DEFINE TABLE/FIELD/INDEX` statements.
/// **Phase 2** — Graph: upserts `doctype`/`docfield` graph nodes and
///               `has_field` RELATE edges with provenance metadata.
///
/// Both phases are fully additive — nothing is ever removed.
pub async fn ensure_schema(adapter: &DbAdapter, meta: &DocTypeMeta) -> Result<(), DbError> {
    let table    = doctype_to_table(&meta.name);
    let safe_name = meta.name.replace([' ', '-'], "_").to_lowercase();

    // 1. Table definition
    let sql = format!(
        "DEFINE TABLE IF NOT EXISTS `{table}` SCHEMAFULL \
         COMMENT 'SpotLedger DocType: {name}';",
        name = meta.name
    );
    adapter.execute(&sql, vec![]).await?;
    tracing::debug!(doctype = %meta.name, "DEFINE TABLE done");

    // 2. System fields — use OVERWRITE so type changes (e.g. option<> → concrete)
    //    propagate to tables that were already defined in a prior startup.
    for (fieldname, ty) in SYSTEM_FIELDS {
        define_system_field(adapter, &table, fieldname, ty).await?;
    }

    // 3. Child-table extra fields
    if meta.is_child {
        for (fieldname, ty) in CHILD_FIELDS {
            define_system_field(adapter, &table, fieldname, ty).await?;
        }
    }

    // 4. DocType-declared fields
    for df in &meta.fields {
        if df.fieldtype.is_layout() {
            continue;
        }
        let Some(ty) = surql_type(&df.fieldtype) else { continue };

        // Nullable override: if not_nullable AND has a default, use non-option type
        let effective_type = if df.not_nullable && !ty.starts_with("option<") {
            ty.to_owned()
        } else if df.not_nullable && ty.starts_with("option<") {
            // strip the option<> wrapper
            ty[7..ty.len() - 1].to_owned()
        } else {
            ty.to_owned()
        };

        let mut sql = format!(
            "DEFINE FIELD IF NOT EXISTS `{fn}` ON TABLE `{table}` TYPE {ty} PERMISSIONS FULL",
            r#fn = df.fieldname,
            ty = effective_type,
        );

        // Attach DEFAULT — explicit value wins; Check fields default to 0
        if let Some(ref dv) = df.default_value {
            match df.fieldtype {
                FieldType::Int | FieldType::Check => {
                    sql.push_str(&format!(" DEFAULT {dv}"));
                }
                FieldType::Float | FieldType::Currency | FieldType::Percent | FieldType::Rating => {
                    sql.push_str(&format!(" DEFAULT {dv}"));
                }
                _ => {
                    // String/text — quote the value
                    let escaped = dv.replace('\'', "\\'");
                    sql.push_str(&format!(" DEFAULT '{escaped}'"));
                }
            }
        } else if df.fieldtype == FieldType::Check {
            // Check (boolean flag) is always 0 when absent — avoids NONE
            // coercion errors on SCHEMAFULL tables
            sql.push_str(" DEFAULT 0");
        }

        sql.push(';');
        adapter.execute(&sql, vec![]).await?;
    }

    // 5. Unique index on `name` (not needed for child tables — parent+idx is the key)
    if !meta.is_child {
        let sql = format!(
            "DEFINE INDEX IF NOT EXISTS idx_{safe_name}_name \
             ON TABLE `{table}` FIELDS name UNIQUE;"
        );
        adapter.execute(&sql, vec![]).await?;
    }

    // 6. Extra indexes: unique fields and standard-filter fields
    for df in &meta.fields {
        if df.fieldtype.is_layout() { continue; }

        if df.unique {
            let idx_name = format!("idx_{safe_name}_{fn}_uq", r#fn = df.fieldname);
            let sql = format!(
                "DEFINE INDEX IF NOT EXISTS `{idx_name}` \
                 ON TABLE `{table}` FIELDS `{fn}` UNIQUE;",
                r#fn = df.fieldname
            );
            adapter.execute(&sql, vec![]).await?;
        }

        if df.in_standard_filter {
            let idx_name = format!("idx_{safe_name}_{fn}", r#fn = df.fieldname);
            let sql = format!(
                "DEFINE INDEX IF NOT EXISTS `{idx_name}` \
                 ON TABLE `{table}` FIELDS `{fn}`;",
                r#fn = df.fieldname
            );
            adapter.execute(&sql, vec![]).await?;
        }
    }

    tracing::info!(doctype = %meta.name, table = %table, "Schema DDL synced (Phase 1)");

    // ── Phase 2: upsert graph nodes + edges ───────────────────────────────────
    ensure_meta_records(adapter, meta, "spotledger", None).await?;

    Ok(())
}

/// Helper — emit one `DEFINE FIELD IF NOT EXISTS` statement (user-defined fields).
async fn define_field(
    adapter: &DbAdapter,
    table: &str,
    fieldname: &str,
    ty: &str,
) -> Result<(), DbError> {
    let sql = format!(
        "DEFINE FIELD IF NOT EXISTS `{fieldname}` ON TABLE `{table}` TYPE {ty} PERMISSIONS FULL;"
    );
    adapter.execute(&sql, vec![]).await
}

/// Helper — emit one `DEFINE FIELD OVERWRITE` statement (system fields).
/// Using OVERWRITE ensures type changes (e.g. option<string> → string) take
/// effect on tables that were created in a previous server startup.
async fn define_system_field(
    adapter: &DbAdapter,
    table: &str,
    fieldname: &str,
    ty: &str,
) -> Result<(), DbError> {
    let sql = format!(
        "DEFINE FIELD OVERWRITE `{fieldname}` ON TABLE `{table}` TYPE {ty} PERMISSIONS FULL;"
    );
    adapter.execute(&sql, vec![]).await
}

// ── Public entry point ────────────────────────────────────────────────────────

/// Run schema sync for **all** compiled DocTypes registered via `inventory`.
///
/// Call this once during `spotledger migrate` or at site startup before
/// accepting any requests.
pub async fn ensure_all_schemas(adapter: &DbAdapter) -> Result<(), DbError> {
    let entries: Vec<_> = inventory::iter::<MetaEntry>.into_iter().collect();

    if entries.is_empty() {
        tracing::warn!("ensure_all_schemas: no MetaEntry registrations found");
        return Ok(());
    }

    tracing::info!(count = entries.len(), "Syncing schemas for compiled DocTypes");

    let mut errors = 0usize;
    let mut error_msgs: Vec<String> = Vec::new();
    for entry in entries {
        let meta = (entry.meta)();
        if let Err(e) = ensure_schema(adapter, &meta).await {
            let msg = format!("{}: {e}", entry.name);
            tracing::error!(doctype = %entry.name, error = %e, "Schema sync failed");
            error_msgs.push(msg);
            errors += 1;
        }
    }

    if errors > 0 {
        return Err(DbError::Other(format!(
            "Schema sync failed for {errors} DocType(s): {}",
            error_msgs.join("; ")
        )));
    }

    Ok(())
}

/// Returns the set of DocType names currently registered in the compiled inventory.
///
/// Used by `spotledger cleanup` to determine which `tabDocField` / `tabDocPerm`
/// rows are orphaned (their parent no longer exists in code).
pub fn compiled_doctype_names() -> std::collections::HashSet<String> {
    inventory::iter::<MetaEntry>
        .into_iter()
        .map(|e| e.name.to_owned())
        .collect()
}

// ── Emit (dry-run generator) ──────────────────────────────────────────────────

/// Generate the SurrealQL that `ensure_schema` would execute for `meta`,
/// without touching the database.
///
/// Used by `spotledger emit` to produce a reviewable `generated/schema.surql`.
pub fn emit_schema_sql(meta: &DocTypeMeta) -> String {
    let table     = crate::document::doctype_to_table(&meta.name);
    let safe_name = meta.name.replace([' ', '-'], "_").to_lowercase();
    let mut out   = String::new();

    out.push_str(&format!(
        "-- ── {name} ──\n\
         DEFINE TABLE IF NOT EXISTS `{table}` SCHEMAFULL \
         COMMENT 'SpotLedger DocType: {name}';\n",
        name = meta.name,
    ));

    for (fieldname, ty) in SYSTEM_FIELDS {
        out.push_str(&format!(
            "DEFINE FIELD IF NOT EXISTS `{fieldname}` ON TABLE `{table}` TYPE {ty};\n"
        ));
    }

    if meta.is_child {
        for (fieldname, ty) in CHILD_FIELDS {
            out.push_str(&format!(
                "DEFINE FIELD IF NOT EXISTS `{fieldname}` ON TABLE `{table}` TYPE {ty};\n"
            ));
        }
    }

    for df in &meta.fields {
        if df.fieldtype.is_layout() {
            continue;
        }
        let Some(ty) = surql_type(&df.fieldtype) else { continue };

        let effective_type = if df.not_nullable && ty.starts_with("option<") {
            ty[7..ty.len() - 1].to_owned()
        } else {
            ty.to_owned()
        };

        let mut line = format!(
            "DEFINE FIELD IF NOT EXISTS `{fn}` ON TABLE `{table}` TYPE {ty} PERMISSIONS FULL",
            r#fn = df.fieldname,
            ty = effective_type,
        );

        if let Some(ref dv) = df.default_value {
            match df.fieldtype {
                FieldType::Int
                | FieldType::Check
                | FieldType::Float
                | FieldType::Currency
                | FieldType::Percent
                | FieldType::Rating => {
                    line.push_str(&format!(" DEFAULT {dv}"));
                }
                _ => {
                    let escaped = dv.replace('\'', "\\'");
                    line.push_str(&format!(" DEFAULT '{escaped}'"));
                }
            }
        }

        line.push(';');
        line.push('\n');
        out.push_str(&line);
    }

    if !meta.is_child {
        out.push_str(&format!(
            "DEFINE INDEX IF NOT EXISTS idx_{safe_name}_name \
             ON TABLE `{table}` FIELDS name UNIQUE;\n"
        ));
    }

    for df in &meta.fields {
        if df.fieldtype.is_layout() { continue; }
        if df.unique {
            let idx_name = format!("idx_{safe_name}_{fn}_uq", r#fn = df.fieldname);
            out.push_str(&format!(
                "DEFINE INDEX IF NOT EXISTS `{idx_name}` \
                 ON TABLE `{table}` FIELDS `{fn}` UNIQUE;\n",
                r#fn = df.fieldname,
            ));
        }
        if df.in_standard_filter {
            let idx_name = format!("idx_{safe_name}_{fn}", r#fn = df.fieldname);
            out.push_str(&format!(
                "DEFINE INDEX IF NOT EXISTS `{idx_name}` \
                 ON TABLE `{table}` FIELDS `{fn}`;\n",
                r#fn = df.fieldname,
            ));
        }
    }

    out
}

/// Generate the full SurrealQL for **all** compiled DocTypes concatenated,
/// preceded by the framework-tables DDL from `bootstrap.rs`.
///
/// Returns `(sql_string, doctype_count)`.
pub fn emit_all_schemas_sql() -> (String, usize) {
    let entries: Vec<_> = inventory::iter::<MetaEntry>.into_iter().collect();
    let count = entries.len();

    let header = format!(
        "-- Generated by `spotledger emit`\n\
         -- Source of truth: compiled Rust DocType definitions\n\
         -- DO NOT EDIT — re-run `spotledger emit` to regenerate\n\
         -- DocTypes: {count}\n\n"
    );

    let body: String = entries
        .iter()
        .map(|e| emit_schema_sql(&(e.meta)()))
        .collect::<Vec<_>>()
        .join("\n");

    (header + &body, count)
}

// ── Phase 2: Metadata-as-Graph ────────────────────────────────────────────────

/// Phase 2 of `ensure_schema`: upsert `doctype` and `docfield` graph nodes and
/// connect them with `has_field` RELATE edges.
///
/// This is idempotent — re-running after adding fields only creates the new
/// edges; existing edges are left untouched.  The `introduced_by` value
/// defaults to `"spotledger"` for compiled Tier 0 types.
pub async fn ensure_meta_records(
    adapter: &DbAdapter,
    meta: &DocTypeMeta,
    introduced_by: &str,
    introduced_version: Option<&str>,
) -> Result<(), DbError> {
    let dt_node = meta.name.to_lowercase().replace([' ', '-'], "_");

    // ── 1. Upsert the doctype graph node ─────────────────────────────────────
    let upsert_dt = format!(
        "UPSERT doctype:{dt_id} CONTENT $content;",
        dt_id = dt_node,
    );
    adapter
        .execute(
            &upsert_dt,
            vec![(
                "content".into(),
                serde_json::json!({
                    "name":                meta.name,
                    "module":              meta.module,
                    "is_single":           if meta.is_single { 1 } else { 0 },
                    "is_child":            if meta.is_child  { 1 } else { 0 },
                    "is_submittable":      if meta.is_submittable { 1 } else { 0 },
                    "is_tree":             if meta.is_tree { 1 } else { 0 },
                    "introduced_by":       introduced_by,
                    "introduced_version":  introduced_version,
                }),
            )],
        )
        .await?;

    // ── 2. Upsert each docfield graph node + RELATE edge ─────────────────────
    for (idx, df) in meta.fields.iter().enumerate().filter(|(_, f)| !f.fieldtype.is_layout()) {
        let df_id = format!(
            "{}_{}",
            dt_node,
            df.fieldname.to_lowercase()
        );

        // Upsert the docfield node
        let upsert_df = format!("UPSERT docfield:{df_id} CONTENT $content;");
        adapter
            .execute(
                &upsert_df,
                vec![(
                    "content".into(),
                    serde_json::json!({
                        "name":         format!("{}_{}", meta.name, df.fieldname),
                        "fieldname":    df.fieldname,
                        "label":        df.label,
                        "fieldtype":    format!("{:?}", df.fieldtype),
                        "reqd":         if df.reqd { 1 } else { 0 },
                        "unique":       if df.unique { 1 } else { 0 },
                        "read_only":    if df.read_only { 1 } else { 0 },
                        "hidden":       if df.hidden { 1 } else { 0 },
                        "in_list_view": if df.in_list_view { 1 } else { 0 },
                        "in_standard_filter": if df.in_standard_filter { 1 } else { 0 },
                        "bold":         if df.bold { 1 } else { 0 },
                        "description":  df.description,
                        "default_value": df.default_value,
                    }),
                )],
            )
            .await?;

        // RELATE doctype -[has_field]-> docfield (IF NOT EXISTS semantics via
        // the unique index on in+out; SurrealDB ignores duplicate RELATE).
        let relate_sql = format!(
            "IF NOT (SELECT * FROM has_field WHERE in = doctype:{dt_id} AND out = docfield:{df_id}) THEN \
               RELATE doctype:{dt_id} -> has_field -> docfield:{df_id} CONTENT $edge; \
             END;",
            dt_id = dt_node,
            df_id = &df_id,
        );
        adapter
            .execute(
                &relate_sql,
                vec![(
                    "edge".into(),
                    serde_json::json!({
                        "idx":                    idx,
                        "introduced_by":          introduced_by,
                        "introduced_version":     introduced_version,
                        "is_custom":              0,
                        "protected":              1,
                        "removable_on_uninstall": 0,
                    }),
                )],
            )
            .await?;
    }

    // ── 3. Upsert tabDocType so boot info / Command Palette can discover this
    //        compiled doctype without requiring a manual `seed-doctypes` run.
    //        The upsert is idempotent and never overwrites fields already set
    //        by seed-doctypes or the designer.
    {
        use crate::document::upsert_doc;
        let mut row = serde_json::json!({
            "doctype":        "DocType",
            "name":           meta.name,
            "module":         meta.module,
            "istable":        if meta.is_child       { 1i64 } else { 0i64 },
            "issingle":       if meta.is_single      { 1i64 } else { 0i64 },
            "issubmittable":  if meta.is_submittable { 1i64 } else { 0i64 },
            "istree":         if meta.is_tree        { 1i64 } else { 0i64 },
            "owner":          "Administrator",
            "modified_by":    "Administrator",
        });
        // Include autoname from compiled meta so fn::naming::resolve works for
        // Tier-0 doctypes (e.g. User: "field:email") without requiring seed-doctypes.
        // upsert_doc uses SET so this never overwrites a value already in the DB.
        if let Some(autoname) = &meta.autoname {
            if let Some(obj) = row.as_object_mut() {
                obj.insert("autoname".into(), serde_json::Value::String(autoname.clone()));
            }
        }
        if let Err(e) = upsert_doc(adapter, "DocType", &meta.name, &row).await {
            tracing::warn!(doctype = %meta.name, error = %e,
                "Could not upsert tabDocType row — boot info may not list this doctype");
        }
    }

    tracing::debug!(
        doctype = %meta.name,
        "Graph meta records ensured (Phase 2)",
    );
    Ok(())
}

// ── Framework module seeding ──────────────────────────────────────────────────

/// Idempotently ensure that every framework module from [`FM::FRAMEWORK_MODULES`]
/// has a corresponding row in `tabModule_Def`.
///
/// Called at server startup (after `ensure_all_schemas`) so that the sidebar
/// module list and the designer module-picker autocomplete work without an
/// explicit `install-app` or `seed-doctypes` step.
pub async fn seed_framework_modules(adapter: &DbAdapter) -> Result<(), crate::error::DbError> {
    use crate::document::upsert_doc;
    use serde_json::json;

    for m in FM::FRAMEWORK_MODULES {
        let show: i64 = if m.show_in_menu { 1 } else { 0 };
        let row = json!({
            "name":         m.name,
            "doctype":      "Module Def",
            "module_name":  m.name,
            "app_name":     m.app,
            "label":        m.label,
            "icon":         m.icon,
            "order":        m.order,
            "show_in_menu": show,
            "owner":        "Administrator",
            "modified_by":  "Administrator"
        });
        if let Err(e) = upsert_doc(adapter, "Module Def", m.name, &row).await {
            tracing::warn!(module = %m.name, error = %e, "Could not seed Module Def — skipping");
        }
    }

    tracing::info!(count = FM::FRAMEWORK_MODULES.len(), "Framework Module Def records ensured");
    Ok(())
}

// ── User-doctype DDL sync ─────────────────────────────────────────────────────

/// Apply `DEFINE TABLE` + `DEFINE FIELD OVERWRITE` DDL for every user-created
/// DocType stored in `tabDocType`.
///
/// Compiled (Tier-0) types are already handled by `ensure_all_schemas`; this
/// function covers everything created via the designer at runtime.  It is safe
/// to run at every startup because all DEFINE statements are idempotent.
///
/// Call this at server startup AFTER `ensure_all_schemas` so system fields on
/// compiled tables are already set before user tables are processed.
pub async fn sync_user_doctype_schemas(adapter: &DbAdapter) -> Result<(), DbError> {
    use crate::document::doctype_to_table;

    let compiled = compiled_doctype_names();

    // Fetch all DocType names in the DB
    let dt_rows = adapter
        .run("SELECT name, istable FROM tabDocType", vec![])
        .await
        .unwrap_or_default();

    if dt_rows.is_empty() {
        return Ok(());
    }

    let mut synced = 0usize;
    let mut errors = 0usize;

    for dt_row in &dt_rows {
        let dt_name = match dt_row.get("name").and_then(|v| v.as_str()) {
            Some(n) => n.to_owned(),
            None => continue,
        };

        // Skip compiled types — already handled by ensure_all_schemas
        if compiled.contains(&dt_name) {
            continue;
        }

        let is_child = match dt_row.get("istable") {
            Some(serde_json::Value::Bool(b)) => *b,
            Some(serde_json::Value::Number(n)) => n.as_u64().unwrap_or(0) != 0,
            _ => false,
        };

        let table     = doctype_to_table(&dt_name);
        let safe_name = dt_name.replace([' ', '-'], "_").to_lowercase();

        // 1. Table definition
        let tbl_sql = format!(
            "DEFINE TABLE IF NOT EXISTS `{table}` SCHEMAFULL \
             COMMENT 'SpotLedger DocType: {dt_name}';"
        );
        if let Err(e) = adapter.execute(&tbl_sql, vec![]).await {
            tracing::error!(doctype = %dt_name, error = %e, "sync_user: DEFINE TABLE failed");
            errors += 1;
            continue;
        }

        // 2. System fields
        for (fieldname, ty) in SYSTEM_FIELDS {
            let sql = format!(
                "DEFINE FIELD IF NOT EXISTS `{fieldname}` ON TABLE `{table}` TYPE {ty} PERMISSIONS FULL;"
            );
            if let Err(e) = adapter.execute(&sql, vec![]).await {
                tracing::warn!(doctype = %dt_name, field = %fieldname, error = %e,
                    "sync_user: system field DDL failed");
            }
        }
        if is_child {
            for (fieldname, ty) in CHILD_FIELDS {
                let sql = format!(
                    "DEFINE FIELD IF NOT EXISTS `{fieldname}` ON TABLE `{table}` TYPE {ty} PERMISSIONS FULL;"
                );
                if let Err(e) = adapter.execute(&sql, vec![]).await {
                    tracing::warn!(doctype = %dt_name, field = %fieldname, error = %e,
                        "sync_user: child field DDL failed");
                }
            }
        }

        // 3. User fields (OVERWRITE so missing ones are always (re-)added)
        // NOTE: SurrealDB v3 requires ORDER BY fields to appear in the SELECT list.
        let field_rows = adapter
            .run(
                "SELECT fieldname, fieldtype, default_value, not_nullable, idx \
                 FROM tabDocField WHERE parent = $dt AND parenttype = 'DocType' ORDER BY idx ASC",
                vec![("dt".into(), serde_json::Value::String(dt_name.clone()))],
            )
            .await
            .unwrap_or_else(|e| {
                tracing::warn!(doctype = %dt_name, error = %e, "sync_user: tabDocField query failed");
                vec![]
            });

        tracing::debug!(doctype = %dt_name, field_count = field_rows.len(), "sync_user: fields loaded");

        for frow in &field_rows {
            let fieldname = match frow.get("fieldname").and_then(|v| v.as_str()) {
                Some(f) => f.to_owned(),
                None => continue,
            };
            let fieldtype = frow.get("fieldtype").and_then(|v| v.as_str()).unwrap_or("Data");

            let surql_ty = match fieldtype.to_lowercase().replace('-', " ").as_str() {
                "check" | "int"                             => "none | int",
                "float" | "currency" | "percent" | "rating" => "float",
                "datetime"                                  => "option<datetime>",
                "date" | "time"                             => "option<string>",
                "table" | "table multiselect"               => "array<any>",
                "json"                                      => "any",
                "section break" | "column break" | "tab break" => continue, // layout only
                _                                           => "option<string>",
            };

            let not_nullable = match frow.get("not_nullable") {
                Some(serde_json::Value::Bool(b)) => *b,
                Some(serde_json::Value::Number(n)) => n.as_u64().unwrap_or(0) != 0,
                _ => false,
            };
            let effective_ty = if not_nullable && surql_ty.starts_with("option<") {
                surql_ty[7..surql_ty.len() - 1].to_owned()
            } else {
                surql_ty.to_owned()
            };

            let default_value = frow.get("default_value").and_then(|v| v.as_str()).unwrap_or("");

            let mut sql = format!(
                "DEFINE FIELD OVERWRITE `{fieldname}` ON TABLE `{table}` TYPE {effective_ty} PERMISSIONS FULL"
            );
            if !default_value.is_empty() {
                let is_numeric = matches!(
                    fieldtype.to_lowercase().as_str(),
                    "check" | "int" | "float" | "currency" | "percent" | "rating"
                );
                if is_numeric {
                    sql.push_str(&format!(" DEFAULT {default_value}"));
                } else {
                    let escaped = default_value.replace('\'', "\\'");
                    sql.push_str(&format!(" DEFAULT '{escaped}'"));
                }
            } else if fieldtype.eq_ignore_ascii_case("Check") {
                sql.push_str(" DEFAULT 0");
            }
            sql.push(';');

            tracing::debug!(doctype = %dt_name, field = %fieldname, sql = %sql, "sync_user: executing field DDL");
            if let Err(e) = adapter.execute(&sql, vec![]).await {
                tracing::warn!(doctype = %dt_name, field = %fieldname, error = %e,
                    "sync_user: user field DDL failed");
            } else {
                tracing::debug!(doctype = %dt_name, field = %fieldname, "sync_user: field DDL ok");
            }
        }

        // 4. Unique name index
        if !is_child {
            let idx_sql = format!(
                "DEFINE INDEX IF NOT EXISTS idx_{safe_name}_name \
                 ON TABLE `{table}` FIELDS name UNIQUE;"
            );
            if let Err(e) = adapter.execute(&idx_sql, vec![]).await {
                tracing::warn!(doctype = %dt_name, error = %e, "sync_user: name index failed");
            }
        }

        synced += 1;
        tracing::debug!(doctype = %dt_name, "sync_user: schema synced");
    }

    tracing::info!(synced, errors, "User doctype schema sync complete");
    Ok(())
}

// ── apply_naming_functions ────────────────────────────────────────────────────

/// Applies the framework naming SurrealDB functions at server startup.
///
/// These are normally loaded by `apply_pipeline_functions` during `install-app`,
/// but embedding them here ensures they are available on every site boot
/// regardless of whether any app has been installed.
///
/// All `DEFINE FUNCTION OVERWRITE` statements are idempotent.
pub async fn apply_naming_functions(adapter: &DbAdapter) -> Result<(), DbError> {
    const NAMING_SURQL: &str =
        include_str!("../../../apps/spotledger-core/spotledger-core/surql/framework/05_naming.surql");

    adapter.execute(NAMING_SURQL, vec![]).await.map_err(|e| {
        DbError::Other(format!("apply_naming_functions failed: {e}"))
    })?;
    tracing::debug!("Naming functions applied");
    Ok(())
}

// ── apply_permissions_functions ───────────────────────────────────────────────

/// Applies the framework permission SurrealDB functions at server startup.
///
/// Defines `fn::permissions::has`, `fn::permissions::get_all`, and
/// `fn::permissions::get_roles` so permission checks are executed as a single
/// graph traversal inside SurrealDB rather than two separate Rust queries.
///
/// All `DEFINE FUNCTION OVERWRITE` statements are idempotent.
pub async fn apply_permissions_functions(adapter: &DbAdapter) -> Result<(), DbError> {
    const PERMISSIONS_SURQL: &str =
        include_str!("../../../apps/spotledger-core/spotledger-core/surql/framework/06_permissions.surql");

    adapter.execute(PERMISSIONS_SURQL, vec![]).await.map_err(|e| {
        DbError::Other(format!("apply_permissions_functions failed: {e}"))
    })?;
    tracing::debug!("Permission functions applied");
    Ok(())
}

// ── apply_pipeline_bootstrap ──────────────────────────────────────────────────

/// Bootstrap the pipeline infrastructure at server startup.
///
/// Applies (in order):
///   1. `01_schema.surql`            — DDL for `pipeline_stage`, `pipeline_node`, `has_node`
///   2. Shared fn:: files            — `fn::validate::mandatory_fields`, `fn::validate::party_check`, etc.
///   3. `02_runner.surql`            — `fn::pipeline::run`
///   4. `03_universal_nodes.surql`   — idempotent upsert of shared `pipeline_node` records
///   5. `04_wire_generic.surql`      — `fn::pipeline::wire_generic`
///   6. Registry rebuild             — `fn::registry::dispatch` covering shared fns + any
///                                     user-defined functions already in `pipeline_node`
///
/// All DDL uses `IF NOT EXISTS` / `OVERWRITE` — fully idempotent and safe to
/// run on every server start regardless of whether `install-app` has been run.
pub async fn apply_pipeline_bootstrap(adapter: &DbAdapter) -> Result<(), DbError> {
    use crate::apply_surql::{apply_registry, collect_fn_names};

    const SCHEMA_SURQL: &str =
        include_str!("../../../apps/spotledger-core/spotledger-core/surql/framework/01_schema.surql");
    const SHARED_MANDATORY: &str =
        include_str!("../../../apps/spotledger-core/spotledger-core/surql/shared/fn_validate_mandatory.surql");
    const SHARED_PARTY: &str =
        include_str!("../../../apps/spotledger-core/spotledger-core/surql/shared/fn_validate_party.surql");
    const SHARED_CANCEL: &str =
        include_str!("../../../apps/spotledger-core/spotledger-core/surql/shared/fn_validate_cancel.surql");
    const SHARED_ON_CANCEL: &str =
        include_str!("../../../apps/spotledger-core/spotledger-core/surql/shared/fn_on_cancel_mark_cancelled.surql");
    const RUNNER_SURQL: &str =
        include_str!("../../../apps/spotledger-core/spotledger-core/surql/framework/02_runner.surql");
    const UNIVERSAL_NODES_SURQL: &str =
        include_str!("../../../apps/spotledger-core/spotledger-core/surql/framework/03_universal_nodes.surql");
    const WIRE_GENERIC_SURQL: &str =
        include_str!("../../../apps/spotledger-core/spotledger-core/surql/framework/04_wire_generic.surql");
    const FN_SOURCE_DDL: &str = "DEFINE TABLE IF NOT EXISTS fn_source SCHEMALESS;";

    // 1. Pipeline table DDL
    adapter.execute(SCHEMA_SURQL, vec![]).await.map_err(|e| {
        DbError::Other(format!("pipeline bootstrap: schema DDL failed: {e}"))
    })?;

    // 2. Shared fn:: definitions
    for (name, sql) in [
        ("fn_validate_mandatory", SHARED_MANDATORY),
        ("fn_validate_party",     SHARED_PARTY),
        ("fn_validate_cancel",    SHARED_CANCEL),
        ("fn_on_cancel",          SHARED_ON_CANCEL),
    ] {
        adapter.execute(sql, vec![]).await.map_err(|e| {
            DbError::Other(format!("pipeline bootstrap: shared fn {name} failed: {e}"))
        })?;
    }

    // 3. Runner (needs registry — applied before universal nodes, then registry is rebuilt after)
    adapter.execute(RUNNER_SURQL, vec![]).await.map_err(|e| {
        DbError::Other(format!("pipeline bootstrap: runner failed: {e}"))
    })?;

    // 4. Universal pipeline_node records (IF NOT EXISTS guards — idempotent)
    adapter.execute(UNIVERSAL_NODES_SURQL, vec![]).await.map_err(|e| {
        DbError::Other(format!("pipeline bootstrap: universal nodes failed: {e}"))
    })?;

    // 5. wire_generic helper
    adapter.execute(WIRE_GENERIC_SURQL, vec![]).await.map_err(|e| {
        DbError::Other(format!("pipeline bootstrap: wire_generic failed: {e}"))
    })?;

    // 6. fn_source table
    adapter.execute(FN_SOURCE_DDL, vec![]).await.map_err(|e| {
        DbError::Other(format!("pipeline bootstrap: fn_source DDL failed: {e}"))
    })?;

    // 7. Build registry: start with shared fn names (embedded), then extend
    //    with any user-defined functions already stored in pipeline_node.
    let mut fn_set: std::collections::BTreeSet<String> = [
        SHARED_MANDATORY,
        SHARED_PARTY,
        SHARED_CANCEL,
        SHARED_ON_CANCEL,
    ]
    .iter()
    .flat_map(|src| collect_fn_names(src))
    .collect();

    // Add any user-defined pipeline_node fn_names (from designer-saved functions).
    let node_rows = adapter
        .run("SELECT fn_name FROM pipeline_node ORDER BY fn_name ASC", vec![])
        .await
        .unwrap_or_default();
    for row in &node_rows {
        if let Some(fn_name) = row.get("fn_name").and_then(serde_json::Value::as_str) {
            if !fn_name.starts_with("fn::pipeline::") && !fn_name.starts_with("fn::registry::") {
                fn_set.insert(fn_name.to_owned());
            }
        }
    }

    let fn_names: Vec<String> = fn_set.into_iter().collect();
    apply_registry(adapter, &fn_names).await.map_err(|e| {
        DbError::Other(format!("pipeline bootstrap: registry rebuild failed: {e}"))
    })?;

    tracing::debug!(registry_size = fn_names.len(), "Pipeline bootstrap complete");
    Ok(())
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use spotledger_core::meta::FieldType;

    #[test]
    fn surql_type_mapping() {
        assert_eq!(surql_type(&FieldType::Check),    Some("none | int"));
        assert_eq!(surql_type(&FieldType::Int),      Some("none | int"));
        assert_eq!(surql_type(&FieldType::Float),    Some("float"));
        assert_eq!(surql_type(&FieldType::Currency), Some("float"));
        assert_eq!(surql_type(&FieldType::Datetime), Some("option<datetime>"));
        assert_eq!(surql_type(&FieldType::Date),     Some("option<string>"));
        assert_eq!(surql_type(&FieldType::Table),    Some("array<any>"));
        assert_eq!(surql_type(&FieldType::Json),     Some("any"));
        assert_eq!(surql_type(&FieldType::Data),     Some("option<string>"));
        assert_eq!(surql_type(&FieldType::SectionBreak), None);
        assert_eq!(surql_type(&FieldType::ColumnBreak),  None);
    }
}
