[package]
name        = "spotledger-geo"
description = "Spotledger — Geo module (Currency, Country)"
version.workspace     = true
edition.workspace     = true
authors.workspace     = true
license.workspace     = true
repository.workspace  = true

[dependencies]
spotledger-core = { workspace = true }
inventory       = { workspace = true }
