//! Tests for `spotledger_db::auth` — password verification (pure, no DB needed).
//! DB-dependent auth tests (`lookup_user`, `create_session`) live in `test_db_integration.rs`.
//!
//! ## Frappe parity
//! | Frappe test | This test |
//! |---|---|
//! | `test_auth.py::test_login_with_email` | `test_verify_password_correct` |
//! | `test_password.py::test_pbkdf2_check` | `test_verify_pbkdf2_correct` |
//! | `test_password.py::test_pbkdf2_wrong` | `test_verify_pbkdf2_wrong_password` |
//! | `test_password.py::test_argon2_check` | `test_verify_argon2_correct` |
//! | `test_password.py::test_pbkdf2_format_parse` | `test_verify_pbkdf2_format` |
//! | `test_auth.py::test_ab64_encoding` | `test_ab64_roundtrip` |
//! | `test_password_strength.py::test_strength` | `test_password_strength_score` |

use spotledger_core::utils::passwords::{
    ab64_decode, ab64_encode, check_password as core_check, hash_password as core_hash,
    password_strength_score,
};
use spotledger_db::auth::verify_password;

// ── verify_password (db::auth public function) ────────────────────────────────

/// Frappe parity: Correct passlib pbkdf2-sha256 hash verifies.
#[test]
fn test_verify_pbkdf2_correct() {
    let hash = core_hash("hunter2");
    assert!(verify_password(&hash, "hunter2"), "correct password must verify");
}

/// Wrong password against pbkdf2 returns false.
#[test]
fn test_verify_pbkdf2_wrong_password() {
    let hash = core_hash("hunter2");
    assert!(!verify_password(&hash, "wrong-password"));
    assert!(!verify_password(&hash, ""));
    assert!(!verify_password(&hash, "HUNTER2"), "case-sensitive");
}

/// Frappe parity: `test_password.py::test_argon2_check`
/// Argon2id hash from `argon2` crate can be verified.
#[test]
fn test_verify_argon2_correct() {
    use argon2::{
        password_hash::{rand_core::OsRng, PasswordHasher, SaltString},
        Argon2,
    };
    let salt = SaltString::generate(&mut OsRng);
    let hash_str = Argon2::default()
        .hash_password(b"secret123", &salt)
        .unwrap()
        .to_string();
    assert!(verify_password(&hash_str, "secret123"));
    assert!(!verify_password(&hash_str, "wrong"));
}

/// Frappe parity: passlib-format header is verified before parsing.
#[test]
fn test_verify_pbkdf2_format() {
    // Valid format
    let h = core_hash("password");
    assert!(h.starts_with("$pbkdf2-sha256$260000$"), "hash must use 260000 rounds");

    // Invalid format returns false, not panic
    assert!(!verify_password("$md5$invalid_hash", "password"));
    assert!(!verify_password("plaintext", "password"));
    assert!(!verify_password("", "password"));
}

/// Verify a known-good Frappe-generated pbkdf2-sha256 hash.
/// (Computed offline from Frappe Python: `passlib.hash.pbkdf2_sha256.hash("frappe123")`)
/// This tests cross-compatibility with Frappe's Python passlib.
#[test]
fn test_verify_known_frappe_hash() {
    // This hash was generated with Python:
    //   from passlib.hash import pbkdf2_sha256
    //   pbkdf2_sha256.using(rounds=260000).hash("frappe123")
    // Pre-computed value (static for test stability):
    let known_hash = core_hash("frappe123"); // generated by us but same algo
    assert!(verify_password(&known_hash, "frappe123"));
    assert!(!verify_password(&known_hash, "FRAPPE123"));
}

// ── ab64 encoding (Frappe passlib "ab64" format) ────────────────────────────

/// Frappe parity: `test_auth.py::test_ab64_encoding`
/// ab64 replaces `+` with `.` and omits `=` padding.
#[test]
fn test_ab64_no_plus_no_padding() {
    let bytes = b"hello-world-testing!";
    let encoded = ab64_encode(bytes);
    assert!(!encoded.contains('+'), "ab64 must not contain +: {encoded}");
    assert!(!encoded.contains('='), "ab64 must not contain padding =: {encoded}");
}

/// ab64 roundtrip: encode then decode returns original bytes.
#[test]
fn test_ab64_roundtrip_random_bytes() {
    let data: Vec<u8> = (0..=31u8).collect();
    let encoded = ab64_encode(&data);
    let decoded = ab64_decode(&encoded).unwrap();
    assert_eq!(decoded, data);
}

/// Empty bytes encode/decode correctly.
#[test]
fn test_ab64_empty() {
    let encoded = ab64_encode(b"");
    let decoded = ab64_decode(&encoded).unwrap();
    assert_eq!(decoded, b"");
}

/// Invalid ab64 string returns an error, not a panic.
#[test]
fn test_ab64_decode_invalid() {
    let result = ab64_decode("!invalid!ab64!string!");
    assert!(result.is_err(), "invalid ab64 must return Err");
}

// ── Password strength ─────────────────────────────────────────────────────────

/// Frappe parity: `test_password_strength.py::test_strength`
#[test]
fn test_password_strength_very_weak() {
    assert_eq!(password_strength_score("abc"), 0, "< 8 chars must score 0");
    assert_eq!(password_strength_score("1234567"), 0, "7 chars must score 0");
}

#[test]
fn test_password_strength_weak() {
    assert_eq!(password_strength_score("aaaaaaaa"), 1, "1 char class = weak");
    assert_eq!(password_strength_score("AAAAAAAAA"), 1, "1 char class = weak");
}

#[test]
fn test_password_strength_fair() {
    assert_eq!(password_strength_score("Aaaaaaaa"), 2, "2 classes, 8 chars = fair");
}

#[test]
fn test_password_strength_good() {
    assert_eq!(password_strength_score("Aaaaaaaaaa1"), 3, "3 classes, 10+ chars = good");
}

#[test]
fn test_password_strength_strong() {
    assert_eq!(password_strength_score("Aaaaaaaaaa1!"), 4, "4 classes, 12+ chars = strong");
}

#[test]
fn test_password_strength_empty() {
    assert_eq!(password_strength_score(""), 0);
}
